### ISSUE TITLE
Tips for creating a `sentence-transformer` model?

### ISSUE THREAD

**Issue by adri** [elixir-nx/bumblebee#100]
First of all, awesome project! I'm looking forward using many models from here.

One use-case I'm excited about to try out is **semantic search** based on text and images based on [SentenceTransformers](https://www.sbert.net). My first try was to export a model to ONNX and use it in Axon, but I ran into this issue https://github.com/elixir-nx/axon_onnx/issues/48. While I'm still trying to fix that I was wondering...

How do you actually create these models? Did you really implement them with the paper as resource or is there a tip on how to implement them? I'm a machine learning beginner. :-)

**Comment by josevalim** [comment]
We use both the paper and the transformers implementation as reference. :) @jonatanklosko and @seanmor5 may be able to drop more details on implementing your own.

**Comment by seanmor5** [comment]
The HF PyTorch code is also a good reference and very readable. Some of the sentence transformers you're looking for might already be implemented as some are variants of bert, roberta, albert, etc. which we support. If there's a specific architecture that's not supported that you'd like I can look into that one more :)

**Comment by jonatanklosko** [comment]
@adri you use `all-MiniLM-L6-v2` and `all-MiniLM-L6-v1` in the examples respectively, is that it?

**Comment by josevalim** [comment]
@jonatanklosko is it worth adding a task around this or not really?

**Comment by jonatanklosko** [comment]
@adri yeah, it is definitely that pooling. Bumblebee corresponds to Transformers, so you need to do the pooling on top of the model, which `SentenceTransformer` does internally.

@josevalim we will add feature extraction task at some point, but `sentence-transformers` is a more specific case.

**Comment by jonatanklosko** [comment]
FTR here's the `transformers` snippet corresponding to the bumblebee one you posted, and it gives the same output:

```python
import torch
from transformers import BertModel, BertTokenizer

model = BertModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")
tokenizer = BertTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")

emb = model(**tokenizer("Winter dogs", return_tensors="pt")).pooler_output

embs = model(**tokenizer([
    'Two dogs in snow', 
    'Install Jupyter Notebook | Learn How to Install and Use Jupyter Notebook', 
    'A picture of London at night',
    'Fastai on Apple M1 - Deep Learning - fast.ai Course Forums: https://forums.fast.ai/t/fastai-on-apple-m1/86059/50'
], return_tensors="pt", padding=True)).pooler_output

torch.cosine_similarity(emb, embs)
```

```
tensor([0.8791, 0.5514, 0.5671, 0.4869], grad_fn=<SumBackward1>)
```

**Comment by Bogdan1001** [comment]
How to use the same model in Elixir, but for CrossEncoder? When embedding is not needed and pairs given as input.

**Comment by jonatanklosko** [comment]
The `CrossEncoder` also builds on top of the model, so we'd need to implement some bits from [here](https://github.com/UKPLab/sentence-transformers/blob/b86eec31cf0a102ad786ba1ff31bfeb4998d3ca5/sentence_transformers/cross_encoder/CrossEncoder.py). It may be the case that we adapt some of `sentence-transformers` stuff, but I think we want to focus on high-level tasks as in `transformers` and also more models :)

**Comment by thiagopromano** [comment]
If anyone is having trouble reaching the same result from the `SentenceTransformer`, this is the `mean_pooling` that worked for us.

```elixir
defn mean_pooling(model_output, attention_mask) do
  input_mask_expanded = Nx.new_axis(attention_mask, -1)

  model_output
  |> Nx.multiply(input_mask_expanded)
  |> Nx.sum(axes: [1])
  |> Nx.divide(Nx.sum(input_mask_expanded, axes: [1]))
end
```

Where `model_output` is predict result `hidden_state`.

**Comment by trodrigu** [comment]
https://github.com/trodrigu/text_embeddings_elixir/ as an example
