### ISSUE TITLE
Support Stable Diffusion 2

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/bumblebee#111]
It looks like there are some minor things broken for stable diffusion 2-1:

```
** (RuntimeError) conversion failed, expected "attention_head_dim" to be a number, got: [5, 10, 20, 20]
    (bumblebee 0.1.0) lib/bumblebee/shared/converters.ex:20: anonymous fn/3 in Bumblebee.Shared.Converters.convert!/2
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (bumblebee 0.1.0) lib/bumblebee/shared/converters.ex:14: Bumblebee.Shared.Converters.convert!/2
    (bumblebee 0.1.0) lib/bumblebee/diffusion/unet_2d_conditional.ex:341: Bumblebee.HuggingFace.Transformers.Config.Bumblebee.Diffusion.UNet2DConditional.load/2
    (bumblebee 0.1.0) lib/bumblebee.ex:279: Bumblebee.load_spec/2
    (bumblebee 0.1.0) lib/bumblebee.ex:372: Bumblebee.load_model/2
    (stdlib 4.0.1) erl_eval.erl:744: :erl_eval.do_apply/7
    (stdlib 4.0.1) erl_eval.erl:492: :erl_eval.expr/6
```

**Comment by zolrath** [comment]
I'm not sure if these are beyond the scope of this, but Stable Diffusion supports a number of different modes:

1. text-to-image
2. image-to-image
3. inpainting
4. upscaling
5. depth-to-image.

Currently there is support for `text-to-image`, but supporting `image-to-image` and `depth-to-image` would be great additions without requiring the additional UI something like `inpainting` would imply. Though, taking a mask image as an additional argument would likely be a good simple path for `inpainting`.

Depth-to-Image is a volume/shape preserving version of image-to-image introduced in 2.0 which is quite interesting.
https://github.com/Stability-AI/stablediffusion#depth-conditional-stable-diffusion

Would love to see these additional modes supported!
