### ISSUE TITLE
CUDA toolkit 12 just released, EXLA doesn't support

### ISSUE THREAD

**Issue by krainboltgreene** [elixir-nx/bumblebee#112]
I can't really think of a better place for this to be but CUDA Toolkit just released their version 12 and it's hard to find the older versions (latest EXLA supports is 11.8), but you can get it here: https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local

**Comment by seanmor5** [comment]
Thanks! Note that EXLA support for CUDA 12 will depend on TensorFlow, and they are usually a bit behind in updating to latest CUDA

**Comment by krainboltgreene** [comment]
That makes perfect sense.
