### ISSUE TITLE
Nx.LazyContainer not implemented for %Bumblebee.Diffusion.PndmScheduler

### ISSUE THREAD

**Issue by hanrelan** [elixir-nx/bumblebee#123]
Hi!
I'm trying to run Stable Diffusion in Livebook without using the pre-built `Nx.Serving` setup (aka `Bumblebee.Diffusion.StableDiffusion.text_to_image`).

I'm getting stuck though because this call keeps failing:

```
{_state, new_latents} = Bumblebee.Diffusion.PndmScheduler.step(scheduler, scheduler_state, latents, noise_pred) 
```

where `scheduler` comes from `{:ok, scheduler} = Bumblebee.load_scheduler({:hf, repository_id, subdir: "scheduler"})`

The error I'm getting is:
```
** (Protocol.UndefinedError) protocol Nx.LazyContainer not implemented for %Bumblebee.Diffusion.PndmScheduler{num_train_steps: 1000, beta_schedule: :quadratic, beta_start: 8.5e-4, beta_end: 0.012, alpha_clip_strategy: :alpha_zero, timesteps_offset: 1, reduce_warmup: true} of type Bumblebee.Diffusion.PndmScheduler (a struct), data-structures given to defn/Nx must implement either Nx.LazyContainer or Nx.Container. This protocol is implemented for the following type(s): Any, Atom, Complex, Float, Integer, List, Map, Nx.Batch, Nx.Tensor, Tuple
```

I'm not sure why this doesn't work since it seems to be the same call that the `text_to_image` function uses internally. Is it because it's within Livebook? The failing notebook is [here](https://github.com/hanrelan/BumbleBooth/blob/main/StableDiffusion.livemd) (last cell)

**Comment by jonatanklosko** [comment]
@hanrelan good catch! Should be addressed by #124. Also note that you can use `Bumblebee.scheduler_init` and `Bumblebee.scheduler_step`, so that you don't need to call the exact scheduler module on your own :)

**Comment by hanrelan** [comment]
Awesome thanks. I know about the `Bumblebee` functions but wanted to be more explicit here to see exactly what was happening.

I'm curious though - how was this working in the `Bumblebee.Diffusion.StableDiffusion.text_to_image` function? As far as I could tell what I was doing was equivalent so it's surprising to me that works but my call didn't.

**Comment by hanrelan** [comment]
Gotcha thanks!
