### ISSUE TITLE
Stable Diffusion, load previously downloaded model

### ISSUE THREAD

**Issue by ramyma** [elixir-nx/bumblebee#127]
Is it possible to load an already downloaded SD model using a file path, rather than downloading it from Huggingface using the repo name?

I think it would be a nice addition especially that some people might have already some working setup of Stable Diffusion and want to skip downloading the models again.

**Comment by jonatanklosko** [comment]
Hey @ramyma! You can use `{:local, "/path/to/repo/unet"}` pointing to a model directory :)

**Comment by ramyma** [comment]
Thaks @jonatanklosko!
I found it here https://github.com/elixir-nx/bumblebee/blob/e281a15d2aa4a47bfe8d17d7519a6001dc472c98/lib/bumblebee.ex#L733

**Comment by jonatanklosko** [comment]
It's in the documentation too, under [`repository`](https://hexdocs.pm/bumblebee/Bumblebee.html#t:repository/0) :)
