### ISSUE TITLE
Unable to force build of Tokenizers

### ISSUE THREAD

**Issue by lukegalea** [elixir-nx/bumblebee#130]
I'm attempting to get a Google Colab going that runs LiveBook w/ BumbleeBee to give developers easy access to a GPU. The crux is getting everything to work on Ubuntu 18.04 when all the precompiled binaries require newer GLIBC.

Generally that hasn't been a problem for EXLA, but the Tokenizers library (compiled nif via Rustler) isn't behaving correctly.

While Rustler's force_build config option doesn't appear to work at all, setting the env variable TOKENIZERS_BUILD=true works perfectly to compile and launch Livebook, but when running within the livebook, it seems to revert to using the prebuilt binaries.

So, a call to Bumblebee.load_tokenizer results in:

```
** (UndefinedFunctionError) function Tokenizers.Native.from_file/1 is undefined (module Tokenizers.Native is not available)
    (tokenizers 0.2.0) Tokenizers.Native.from_file("/root/.cache/bumblebee/huggingface/hnu6qkd3fooybwwjvnddfafwua.ei2geojyhbrggy3dhfsggnlbmrqwgzbugazwgmbqmi2dombuhe3tmmjzgy2tiodghara")
    (bumblebee 0.1.2) lib/bumblebee/utils/tokenizers.ex:120: Bumblebee.Utils.Tokenizers.load!/1
    (bumblebee 0.1.2) lib/bumblebee/text/gpt2_tokenizer.ex:37: Bumblebee.HuggingFace.Transformers.Config.Bumblebee.Text.Gpt2Tokenizer.load/2
    (bumblebee 0.1.2) lib/bumblebee.ex:577: Bumblebee.load_tokenizer/2
    #cell:f6mspfr4bdyx57zlfg26jfl3c4fqc2gq:2: (file)

22:11:53.535 [warn] The on_load function for module Elixir.Tokenizers.Native returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28\' not found
```

**Comment by lukegalea** [comment]
Jeez. I get it now. The default Livebook runtime is standalone, so it opens a new process that doesn't share the system environment... hence it not respecting TOKENIZERS_BUILD.

Solved by changing to embedded runtime.

**Comment by josevalim** [comment]
Vars should actually be shared. You can set env vars also in the Setting panel and it will apply to all notebooks, regardless if embedded or not.
