### ISSUE TITLE
Cannot set temperature, top-k, etc for GPT-2 models

### ISSUE THREAD

**Issue by lukegalea** [elixir-nx/bumblebee#132]
Text generation tasks are very susceptible to repetition for anything longer than the shortest outputs. How can we set temperature, top-k or other parameters that are normally used to avoid this in GPT-2 output?

![image](https://user-images.githubusercontent.com/17691/208717766-724ce4c4-18ba-429c-8506-85b18f639349.png)

**Comment by josevalim** [comment]
Yes, this is meant to be tracked in #35. :)
