### ISSUE TITLE
Support for stable diffusion >2.0

### ISSUE THREAD

**Issue by lukegalea** [elixir-nx/bumblebee#133]
Stable Diffusion 1.5 works perfectly (might be worth updating the smart cell to point to 1.5 rather than 1.4), but 2.0 and 2.1 need some attention. (Looks like older models only supported one attention head dim and now the models have multiple?): 

```
** (RuntimeError) conversion failed, expected "attention_head_dim" to be a number, got: [5, 10, 20, 20]
    (bumblebee 0.1.2) lib/bumblebee/shared/converters.ex:20: anonymous fn/3 in Bumblebee.Shared.Converters.convert!/2
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (bumblebee 0.1.2) lib/bumblebee/shared/converters.ex:14: Bumblebee.Shared.Converters.convert!/2
    (bumblebee 0.1.2) lib/bumblebee/diffusion/unet_2d_conditional.ex:341: Bumblebee.HuggingFace.Transformers.Config.Bumblebee.Diffusion.UNet2DConditional.load/2
    (bumblebee 0.1.2) lib/bumblebee.ex:279: Bumblebee.load_spec/2
    (bumblebee 0.1.2) lib/bumblebee.ex:372: Bumblebee.load_model/2
    #cell:25h4u7t3mfavivpqrylftjgs5u6ptd3t:10: (file)
```

to reproduce, just use the SD 1.4 smart-cell and replace repository_id with ```repository_id = "stabilityai/stable-diffusion-2-1"```

**Comment by josevalim** [comment]
Please try main @lukegalea! I believe SD 2.0 support was recently merged from #111.

**Comment by lukegalea** [comment]
Perfect! I'll give this a try and report back.

**Comment by jonatanklosko** [comment]
This should be addressed, if you run into any issues feel free to reopen :)
