### ISSUE TITLE
Add support for converting python Pillow image file format into something that Elixir can use

### ISSUE THREAD

**Issue by meanderingstream** [elixir-nx/bumblebee#138]
I considered looking at a dataset in Huggingface, but the images are stored a Pillow format.  I don't believe the images can be read with an Elixir tool.

**Comment by josevalim** [comment]
Can you provide an example of such image, my google-fu failed me. :)

**Comment by meanderingstream** [comment]
I think I didn't read the data card correctly.  Please close.
