### ISSUE TITLE
EXLA compile issue in Livebook

### ISSUE THREAD

**Issue by SlowburnAZ** [elixir-nx/bumblebee#139]
I'm messing around with the Stable Diffusion example, and I'm getting the following error in Livebook when trying to add the exla dependency:

```
could not compile dependency :exla, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exla", update it with "mix deps.update exla" or clean it with "mix deps.clean exla"

** (MatchError) no match of right hand side value: {"x86_64", "windows"}
...
```

Not sure what I could be doing wrong...  any suggestions?

**Comment by josevalim** [comment]
We don’t have precompiled for XLA. Set the XLA_BUILD=true environment variable and you should be good! We improved the error message on XLA main too.

**Comment by SlowburnAZ** [comment]
How does one even set environment variables such as this when running the Windows Livebook application?

**Comment by SlowburnAZ** [comment]
Nevermind...  derp.  Found it in the main Livebook settings, rather than in a particular livebook

**Comment by SlowburnAZ** [comment]
@josevalim 
I've set that environment variable in Livebook settings, but am still getting the same error when trying to add the exla package to a livebook:

![image](https://user-images.githubusercontent.com/5659169/209720707-06be0f5d-a6fe-4181-b3c4-635fd4e0e5c5.png)

![image](https://user-images.githubusercontent.com/5659169/209720878-5ab9e1c6-eb82-4db8-9c35-3b7e40a9c097.png)

Any other suggestions?

**Comment by josevalim** [comment]
The value is “true” only.

**Comment by josevalim** [comment]
And you would need to restart the runtime.

**Comment by SlowburnAZ** [comment]
I had tried that also, but I guess I hadn't restarted the runtime.  

However, even after closing the Livebook app, killing the launcher process and all elixir/erlang processes, and then trying again, it's still not working either...  hmm.

**Comment by seanmor5** [comment]
I think this was actually fixed recently in the XLA git repository wasn't it? Can you try pointing XLA to GitHub main and overriding that dependency to see if it works?

**Comment by SlowburnAZ** [comment]
I feel sorta stupid here, but I can't seem to find the proper URL for just EXLA in git to point to...

**Comment by josevalim** [comment]
There is also a elixir-nx/xla repo, which is just the pre compiled xla. :) and no problem in asking questions!

**Comment by SlowburnAZ** [comment]
Awesome...  that gets me past the compilation issues.  :-)  Now I'm not sure what the equivalent of `Nx.global_default_backend(EXLA.Backend)` would be when using this precompiled xla.

**Comment by josevalim** [comment]
It is the same. :)

**Comment by SlowburnAZ** [comment]
Ok, thanks!

I've been trying to follow along with https://github.com/elixir-nx/bumblebee/blob/main/notebooks/stable_diffusion.livemd

Seems something's still up with the backend:
![image](https://user-images.githubusercontent.com/5659169/209866816-74489eb9-0c3d-4a61-8747-30a7f7b2c3cf.png)


I'm pretty new to using Livebook, so I assume the `Mix.install(...)` and `Nx.global_default_backend(EXLA.Backend)` stuff goes into the "Notebook dependencies and setup" section.

**Comment by josevalim** [comment]
You probably have errors and/or warnings in your first cell (the setup/installation one). We are working on making those warnings more prominent but my hunch is a failed EXLA installation (because XLA failed). Sorry for the confusion but the Windows workflow was not set-up extensively.

**Comment by SlowburnAZ** [comment]
Actually, the setup section looks fine (other than the fact that there's an empty list):
![image](https://user-images.githubusercontent.com/5659169/209876181-46f2a2c4-6e8e-447e-b159-25b617852db9.png)
