### ISSUE TITLE
Consider marking Schedulers as Nx.Containers

### ISSUE THREAD

**Issue by hanrelan** [elixir-nx/bumblebee#150]
Working on Textual Inversion:
https://github.com/hanrelan/BumbleBooth/blob/TextualInversion/StableDiffusion-TextualInversion.livemd
(search for `batch_step`)

It would help if schedulers could be passed in to `defn` methods without passing them as `opts`.

**Comment by jonatanklosko** [comment]
I considered this initially, especially before settling on making scheduler state separate. The struct now only has configuration keys and no tensors, so I wasn't sure if defining the protocol would be justified/idiomatic, especially that for user-facing API we can always use `deftransform`. Passing such structs in custom `defns` is a bit less convenient via options, but that's the tradeoff. @josevalim wdyt?

**Comment by josevalim** [comment]
I believe @hanrelan changed the notebook the pass the only parameter needed explicitly as argument. I would suggest to keep this open for now and collect more feedback. :)

**Comment by josevalim** [comment]
No additional feedback. Gladly to revisit later.
