### ISSUE TITLE
NanoGPT ?

### ISSUE THREAD

**Issue by niccolox** [elixir-nx/bumblebee#152]
cross posting from Elixir Forum (bad form I know)

any thoughts on NanoGPT? https://elixirforum.com/t/nanogpt-and-tiny-ai-in-elixir/53378

**Comment by josevalim** [comment]
The goal of Bumblebee is to provide implementations of pre-trained models where the parameters themselves are available somewhere. NanoGPT is super awesome (as usual from karpathy) and it can load GPT2 weights, but my understanding is that its benefits are mostly about training, which Bumblebee does not provide right now. So I am not sure there is a good fit here.

However, if anyone wants to provide a NanoGPT version on top of Axon, I think that it would be highly educative.
