### ISSUE TITLE
Question Answering Setup in Serving

### ISSUE THREAD

**Issue by blackeuler** [elixir-nx/bumblebee#156]
``` 
@spec serving() :: Nx.Serving.t()
  def serving() do
    {:ok, model_info} = Bumblebee.load_model({:hf, "deepset/roberta-base-squad2-distilled"}, architecture: :for_question_answering)
    {:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, "roberta-base"})

    Bumblebee.Text.generation(model_info, tokenizer, max_new_tokens: 15)
  end

  @spec extract([String.t()]) :: term()
  def extract(input), do: Nx.Serving.batched_run(__MODULE__, input)
```
  
  Trying to use the robert-base for question answering, but I don't seem to be doing something correctly.
  
  `input = ["this is the text for the context", "What is the answer to my question?"]`
  
  And this is the output:
  
  
```
** (KeyError) key :decoder_num_attention_heads not found in: [hidden_size: 768, decoder_attention_heads: 12, encoder_attention_heads: 12, decoder_blocks: 12, encoder_sequence_length: nil]
            (elixir 1.14.2) lib/keyword.ex:595: Keyword.fetch!/2
            (bumblebee 0.1.2) lib/bumblebee/layers/decoder.ex:51: Bumblebee.Layers.Decoder.init_cache/3
            (bumblebee 0.1.2) lib/bumblebee/text/generation.ex:303: Bumblebee.Text.Generation.prepare_decoder_inputs/4
            (bumblebee 0.1.2) lib/bumblebee/text/generation.ex:273: anonymous fn/4 in Bumblebee.Text.Generation.input_callbacks/4
            (bumblebee 0.1.2) lib/bumblebee/text/generation.ex:356: Bumblebee.Text.Generation.generate_impl/7
            (nx 0.4.2) lib/nx/defn/compiler.ex:142: Nx.Defn.Compiler.runtime_fun/3
```

Any help would be appreciated.

**Comment by jonatanklosko** [comment]
Hey @blackeuler! There was a typo in option names, I've just fixed it in main. However, the question answering models do not generate the answer text, instead they find a selection in a large text that best answers the question (so the model returns the start and end position in the text). Consequently this model is not compatible with `Bumblebee.Text.generation`, I also added a validation to show a less confusing error.

We currently don't have a serving for the question answering models, just a bare bones example in [the docs](https://hexdocs.pm/bumblebee/examples.html#question-answering). We do plan to eventually add servings for all types of models though :)

**Comment by blackeuler** [comment]
Are servings a requirement to add these models into a Phoenix app? Thanks for the quick response.

**Comment by blackeuler** [comment]
And I guess another follow-up, would adding that Serving type be a good first issue?

**Comment by jonatanklosko** [comment]
> Are servings a requirement to add these models into a Phoenix app?

Not strictly required, but that's pretty much the way to do it, it encapsulates everything in a single process, so you load the model once, and more importantly batches the requests from multiple clients, which is important in production. Note that you can build your own serving, perhaps looking at the ones in will help.

> And I guess another follow-up, would adding that Serving type be a good first issue?

Yeah, I think a basic serving for question answering shouldn't be too involved based on the docs example I referenced and other servings we have, like image/text classification. The hugginface/transformers library is also our main point of reference, you can see an example [here](https://huggingface.co/tasks/question-answering#inference). The pipeline implementation is [here](https://github.com/huggingface/transformers/blob/bc44e947f371924db854a460484ec46c95e50a35/src/transformers/pipelines/question_answering.py), it likely has more options than we need initially :)

**Comment by blackeuler** [comment]
Thanks, I think I will play around with this. If I make some headway, ill open a PR. Thanks once again
