### ISSUE TITLE
[Feature request] Face detection in Images (Haar cascades or DNN)

### ISSUE THREAD

**Issue by kipcole9** [elixir-nx/bumblebee#158]
If you're still accepting feature requests ..... face detection in images would be fantastic to add.  Similar to the [OpenCV DNN model](https://docs.opencv.org/4.x/d0/dd4/tutorial_dnn_face.html) for example.  This comes up as a topic in every situation from creating image avatars or simply cropping images to the face or faces in an image.

**Comment by jonatanklosko** [comment]
Hey! For object detection there is [DETR](https://huggingface.co/facebook/detr-resnet-50), which we don't have yet and is tracked by #146. I couldn't find any model for face detection specifically on HuggingFace though.

Sidenote: I think Evision supports both Haar and DNN.
