### ISSUE TITLE
Try embedding parameters as part of the compiled module

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/bumblebee#166]
```
predict_fn = Axon.build()
compiled = Nx.Defn.compile(predict_fn)
fn batch -> compiled.(batch, params) end
```

vs

```
predict_fn = Axon.build()
compiled = Nx.Defn.compile(&predict_fn(&1, params))
fn batch -> compiled.(batch) end
```

**Comment by seanmor5** [comment]
Wait, wasn't the reason we initially didn't do this because the params become part of the cache key, so it becomes extremely large?

**Comment by jonatanklosko** [comment]
@josevalim currently we explicitly forbid that (without copying to binary backend) in [this check](https://github.com/elixir-nx/nx/blob/d8a65e936c441ed3ba64f5f82dd402ef46e9a42d/nx/lib/nx/shared.ex#L478-L482).

**Comment by josevalim** [comment]
@seanmor5 @jonatanklosko both good points which shall be temporarily ignored for experimentation purposes :P

**Comment by jonatanklosko** [comment]
Tested it with stable diffusion and it seems to make the runtime much slower (2 times slower on a CPU locally, on a GPU I didn't even get it to finish before crashing).
