### ISSUE TITLE
Support Marian

### ISSUE THREAD

**Issue by pejrich** [elixir-nx/bumblebee#167]
I am curious about what work is required to support the Marian model? From what i've read it appears to be a slight variation on the BART model. Would it be possible to use the Bumblebee implementation of BART to run a Marian model? Or would it require a lot of work to support a Marian model in Bumblebee? Thanks.

**Comment by seanmor5** [comment]
@pejrich you can try the branch in #168

I don't think Marian has a fast tokenizer implementation upstream yet, so that might need to get added

**Comment by pejrich** [comment]
@seanmor5 Sorry, for the late reply, I got side tracked with another project. This is awesome! I'm taking a look at it right now. Thank you so much
