### ISSUE TITLE
Add Image-to-Image Example

### ISSUE THREAD

**Issue by yordis** [elixir-nx/bumblebee#170]
It would be amazing to have some examples of doing Image-to-Image situations. Use a baseline set of images to generate some images with similar styles.

Many thanks for considering my request.

**Comment by josevalim** [comment]
I don’t think we support it yet,, which is why there are no examples. :)

**Comment by jonatanklosko** [comment]
Correct, it's not currently supported, but #120 tracks additional usages of Stable Diffusion that we want to support :)

**Comment by yordis** [comment]
Thank you y'all! I feel really newbie around anything ML related, my apologies for the duplicate issue ...

**Comment by jonatanklosko** [comment]
Sure, no worries!
