### ISSUE TITLE
[Req] Whisper - allow to pass additional data to ffmpeg

### ISSUE THREAD

**Issue by dkuku** [elixir-nx/bumblebee#173]
Some findings I made:
I modified the speech_to_text module - this speeds it up the transcription greatly because it does not load the whole file to a tensor.
I'm chunking my file in 20s chunks - overlapping by 5s. 
And with this change It's twice as fast as when I did not have the -t option.
Also when I was loading the whole file I often got just a few words back comparing to other chunks and no overlapping words. Now 
it seems to transcribe much better
```elixir
diff --git a/lib/bumblebee/audio/speech_to_text.ex b/lib/bumblebee/audio/speech_to_text.ex
index 63e3046..f64d57e 100644
--- a/lib/bumblebee/audio/speech_to_text.ex
+++ b/lib/bumblebee/audio/speech_to_text.ex
@@ -45,6 +45,9 @@ defmodule Bumblebee.Audio.SpeechToText do
           %Nx.Tensor{shape: {_}} = input ->
             {:ok, input}
 
+          {:file, path, seek} when is_binary(path) ->
+            ffmpeg_read_as_pcm(path, sampling_rate, seek)
+
           {:file, path} when is_binary(path) ->
             ffmpeg_read_as_pcm(path, sampling_rate)
 
@@ -64,7 +67,7 @@ defmodule Bumblebee.Audio.SpeechToText do
     end)
   end
 
-  defp ffmpeg_read_as_pcm(path, sampling_rate) do
+  defp ffmpeg_read_as_pcm(path, sampling_rate, seek \\ 0) do
     channels = 1
 
     format =
@@ -84,6 +87,10 @@ defmodule Bumblebee.Audio.SpeechToText do
         System.cmd("ffmpeg", [
           "-i",
           path,
+          "-ss",
+          Integer.to_string(seek),
+          "-t",
+          Integer.to_string(20),
           "-ac",
           Integer.to_string(channels),
           "-ar",
@@ -96,6 +103,9 @@ defmodule Bumblebee.Audio.SpeechToText do
           "pipe:1"
         ])
         |> case do
+          {"", 0} ->
+            {:error, "ffmpeg retured no data"}
+
           {data, 0} ->
             {:ok, Nx.from_binary(data, :f32)}
 
```
My code. (currently it fails when no data is given so I needed to add rescue)
```elixir
0..3600//20
|> Enum.map(fn real_start ->
try do
  start = max(0, real_start - 5)
  Nx.Serving.run(serving, {:file, "/home/kuku/thinking_elixir.mp3", start})
  |> get_in([:results, Access.at(0), :text])
  |> IO.inspect(label: real_start)
rescue _ ->
  ""
end
end
)
```

**Comment by josevalim** [comment]
In this case, our suggestion is to extract the ffmpeg out  and pass all options you need yourself. A PR that documents the `ffmpeg` call alongside the currently used options is welcome!

**Comment by dkuku** [comment]
Can it be extracted to a dependency of bublebee? I'm thinking the about
having speech_to_text as an optional lib or leaving the speech_to_text to
only work with vectors and having something that handles sound files as an
option?

**Comment by josevalim** [comment]
I don't think we need to extract. The support are very few lines of code and it assumes a system dependency. It is mostly convenience to get started and you can invoke it yourself for extra needs.
