### ISSUE TITLE
Context Tokens for Whisper - output timestamps

### ISSUE THREAD

**Issue by wwaldner-amtelco** [elixir-nx/bumblebee#180]
Is there a way to provide the context tokens for the Whisper library? Specifically, I would like the model to output the timestamps(preferable for each word).  Not sure if this is easy to accomplish, but I saw that whisper.cpp allows getting the word level timestamp.  This would be very useful as it would allow me to perform a form of speaker diarisation on the output text.

**Comment by jonatanklosko** [comment]
Hey @wwaldner-amtelco, I think there's no straightforward way as of now, but that's definitely an option we want to support. Also, we are yet to add support for chunking inputs longer than 30s.

**Comment by jonatanklosko** [comment]
Move to #187.
