### ISSUE TITLE
Support transcriptions in Whisper

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/bumblebee#198]
Whisper has a token that signifies "beginning of speech". We should change the output of Whisper to be a list of speeches and their starting points rather than a single text.

This will enable us in the future to do full transcriptions with timestamps for longer audios too.

**Comment by artemk** [comment]
Is there any progress on this? 
Will [long form transcription](https://huggingface.co/openai/whisper-base#long-form-transcription ) be a part of it?

**Comment by josevalim** [comment]
This is already in.
