### ISSUE TITLE
Support ControlNet 1.1 in Stable Diffusion

### ISSUE THREAD

**Issue by zolrath** [elixir-nx/bumblebee#205]
Hello!
I'm not sure the right format to request functionality but [ControlNet](https://jeffwang.substack.com/p/controlnet-11-has-arrived) adds an astounding amount of control and new abilities to Stable Diffusion as seen here:
https://jeffwang.substack.com/p/controlnet-11-has-arrived

It would be amazing to be able to use ControlNet with Stable Diffusion within Elixir!

**Comment by josevalim** [comment]
Our focus at the moment is in supporting a wide range of models. For specialization of the existing models, pull requests are very welcome, but not something we can focus at the moment! :)
