### ISSUE TITLE
How to configure a text-to-speech model forced_token_ids?

### ISSUE THREAD

**Issue by rhcarvalho** [elixir-nx/bumblebee#210]
Thanks for Bumblebee and the provided examples! I'm trying out the example at https://github.com/elixir-nx/bumblebee/blob/main/examples/phoenix/speech_to_text.exs.

It works well for audio input in English. For audio input in other languages, it seems to be automatically translating the output to English.

I read https://huggingface.co/openai/whisper-tiny#usage, and, if I understood it well, I'd need to use `forced_token_ids` to specify the desired/input language and task to be transcribe and not translate. Like in:

```python
processor = WhisperProcessor.from_pretrained("openai/whisper-tiny")
model = WhisperForConditionalGeneration.from_pretrained("openai/whisper-tiny")
forced_decoder_ids = processor.get_decoder_prompt_ids(language="french", task="transcribe")  ## <<<<<

# ...

predicted_ids = model.generate(input_features, forced_decoder_ids=forced_decoder_ids)
transcription = processor.batch_decode(predicted_ids)
['<|startoftranscript|><|fr|><|transcribe|><|notimestamps|> Un vrai travail intéressant va enfin être mené sur ce sujet.<|endoftext|>']
transcription = processor.batch_decode(predicted_ids, skip_special_tokens=True)
[' Un vrai travail intéressant va enfin être mené sur ce sujet.']
```

How to do that with Bumblebee?

**Comment by josevalim** [comment]
Not possible yet, see #187. :)

**Comment by jonatanklosko** [comment]
@rhcarvalho you can customize `forced_token_ids` see https://github.com/elixir-nx/bumblebee/pull/107#issuecomment-1435388630, we want to streamline this in #187 with higher-level options :)
