### ISSUE TITLE
Support Stable Diffusion inpainting

### ISSUE THREAD

**Issue by mvkvc** [elixir-nx/bumblebee#212]
I would like to use the SD 2 inpainting model from https://huggingface.co/stabilityai/stable-diffusion-2-inpainting with Bumblebee. From reviewing the code it doesn't seem like there is support for this as of yet and I would like to add it if possible.

**Comment by josevalim** [comment]
PRs certainly welcome!

**Comment by josevalim** [comment]
Dupe of #120.
