### ISSUE TITLE
AWS neuron/inferentia

### ISSUE THREAD

**Issue by sonic182** [elixir-nx/bumblebee#222]
I think it will be nice to enhance the Bumblebee library (possibly the Axon or XLA components) to support execution of models on AWS Inferentia chips/instances.

Given the cost-effective nature of these specialized ML compute instances, their integration could significantly improve models execution efficiency and performance.

inf1 instances are cheaper than cheaper gpu instances (g4nd I think)

Please refer to [AWS Inferentia](https://aws.amazon.com/machine-learning/inferentia/) and [AWS Neuron](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/) for further context.

**Comment by josevalim** [comment]
Hi @sonic182, Bumblebee is not about the execution of models, it is about implementing models and loading their weights. You are right, this would rather belong on XLA, but the most likely option to see this happening is by external contributions. We would rather focus on more generally available options than focusing on a particular cloud vendor.
