### ISSUE TITLE
Run a sentence similarity model

### ISSUE THREAD

**Issue by pandadefi** [elixir-nx/bumblebee#227]
I would like to run a model like https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2 to get the similarities between several sentences. Is there anything I can try?

**Comment by josevalim** [comment]
Hi @pandadefi, ElixirForum is likely a better place for questions and there is a thread about running and the several approaches we are trying to optimize it if you want to go deeper: https://elixirforum.com/t/nx-vs-python-performance-for-sentence-transformer-encoding/56502
