### ISSUE TITLE
Allow setting `CACHE_DIR` and `BUMBLEBEE_OFFLINE` via Config

### ISSUE THREAD

**Issue by thiagopromano** [elixir-nx/bumblebee#240]
Hey,

I'm wondering why `CACHE_DIR` and `BUMBLEBEE_OFFLINE` options are loaded directly from the system environment variables and not from the application config as is commonly done in other Elixir libraries.

Replacing `System.get_env` with `Application.get_env` would allow greater flexibility. It can default to the env variables for backward compatibility.

**Comment by josevalim** [comment]
This is because they were meant to be used from scripts. See examples/phoenix/README.md that explains how they are used. You can also pass those to as options to Bumblebee itself.

**Comment by jonatanklosko** [comment]
You can pass these and more as `{:hf, "...", opts}`, see [t:repository/0](https://hexdocs.pm/bumblebee/Bumblebee.html#t:repository/0). With that, you are free to use configuration in your app :)
