### ISSUE TITLE
Support for model quantization

### ISSUE THREAD

**Issue by a-alhusaini** [elixir-nx/bumblebee#249]
Running larger models on bumblebee is difficut for people with lower tier hardware.

Adding GPTQ and GGUF/GGML would greatly boost model accessability in the elixir ecosystem.

**Comment by josevalim** [comment]
This is a feature that will be added directly to Nx/EXLA. Currently WIP so stay tuned. :)

**Comment by josevalim** [comment]
We are currently updating XLA in Nx and the new version supports quantization. :) So hopefully sooner than later!

**Comment by josevalim** [comment]
Search for MLIR in the Nx project. Once that is done, we can start thinking about quantization!

**Comment by shaqq** [comment]
> Adding GPTQ and GGUF/GGML would greatly boost model accessability in the elixir ecosystem.

Just to clarify, @josevalim, do you think Nx will be able to run GGUF models? I don't believe XLA will work with GGUF models out of the box, since that's a quantized model file format for llama.cpp:

https://github.com/ggerganov/ggml/blob/master/docs/gguf.md

**Comment by josevalim** [comment]
Those are two separate problems. Once we support quantization, then we may be able to run GGUF, as long as someone writes a deserializer for it.

**Comment by SichangHe** [comment]
Blocking on https://github.com/elixir-nx/nx/issues/1452.
