### ISSUE TITLE
How do you deploy this on Fly.io?

### ISSUE THREAD

**Issue by ndrean** [elixir-nx/bumblebee#270]
Is it possible to deploy the "BLIP/base" Image classification model on a Fly.io free tier? or put in other words, can you provide a working example on how to deploy a model using `Bumblebee` on Fly.io?

What did I do? 
I copied the Dockerfile from [LiveBeats](https://github.com/fly-apps/live_beats/blob/cm-whisper/Dockerfile). I imagine it implements  [the "cached from HF"](https://github.com/elixir-nx/bumblebee/tree/main/examples/phoenix#2-cached-from-hugging-face), meaning a local cache with the env var `BUMBLEBEE_CACHE_DIR` set.

However, when I run this line - from the LiveBeat Dockerfile - in the builder stage:

```bash
RUN mix run -e 'MyApp.Application.serve()' --no-start
```
it fails and I get:

```bash
[output clipped, log limit 100KiB/s reached]
```
> I found another command, `RUN /app/bin/my_app eval 'MyApp.Application.serve'` in [a Fly.io blog](https://fly.io/phoenix-files/speed-up-your-boot-times-with-this-one-dockerfile-trick/), but it fails ("can't find /app/bin/my_app" ???).

I am not sure if this is a Fly.io limitation or if it means something else. 

So ok, don't do this: I omit running "Application.serve()" (see the Application module below).  I have `git` and `curl` installed in the builder. It seems that indeed my image inflated, reaching 575Mb (+ Git for uploading the model as it seems I can't preload and cache it).

However, it seems that: `[info]Out of memory: Killed process`
I can't run this.

 
```elixir
defmodule MyApp.Application do
  use Application

def serve do
    model = "Salesforce/blip-image-captioning-base"
    {:ok, model_info} = Bumblebee.load_model({:hf, model})
    {:ok, featurizer} =
      Bumblebee.load_featurizer({:hf, model})
    {:ok, tokenizer} =
      Bumblebee.load_tokenizer({:hf, model})
    {:ok, generation_config} =
      Bumblebee.load_generation_config({:hf, model})
    generation_config = Bumblebee.configure(generation_config, max_new_tokens: 100)

    _serving =
      Bumblebee.Vision.image_to_text(model_info, featurizer, tokenizer, generation_config,
        compile: [batch_size: 1],
        defn_options: [compiler: EXLA],
        preallocate_params: true
      )
  end

def start(_type, _args) do
    children = [
      {Nx.Serving, serving: serve(), name: MyApp.Serving}
   ]
   opts = [strategy: :one_for_one, name: MyApp.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

**Comment by josevalim** [comment]
Hi @ndrean. Please use the ElixirForum for general questions/help. If you can share your Dockerfile and app in a GitHub repository, it will be easier. 

About the log, does it show anything as it progresses? Maybe it is a download bar or something else posting too much information?

**Comment by josevalim** [comment]
Other things to try out: try saving the model to disk and loading directly from disk.

In any case, if the fly instance has 256MB of memory, I doubt you will be able to run the model. If the model is 990MB compressed, I expect it will require more than when loaded into memory.

**Comment by jonatanklosko** [comment]
@ndrean `can't find /app/bin/my_app` sounds like an issue with your Dockerfile.

Building with cache should be fine, but the model is definitely to big for the free instance. You can look at [this HuggingFace space](https://huggingface.co/spaces/jonatanklosko/chai/tree/main) for an example LV app deployment with Bumblebee stuff. There is a Dockerfile that also downloads the model at build time.

**Comment by ndrean** [comment]
Sorry for polluting, indeed...

@jonatanklosko 
Thks for the link for this dockerfile. 
It uses a GPU I guess with EXLA->CUDA. Then the [build stage](https://huggingface.co/spaces/jonatanklosko/chai/blob/d51dceadd44056d06e571ea2ff335cf695582fe0/Dockerfile#L52) does:

```
# Start the app to download models into the cache
RUN SECRET_KEY_BASE="$(mix phx.gen.secret)" mix app.start
```

Whilst [LiveBeats with Whispers](https://github.com/fly-apps/live_beats/blob/57f5c0f14277c6e476b9998c953e58d7deb0cd9d/Dockerfile#L61) does as below, and my Dockerfile is just generated by Fly, so just a copy.

```
RUN mix run -e 'LiveBeats.Application.load_serving()' --no-start
```

I will observe the memory used.

**Comment by jonatanklosko** [comment]
Yeah, I did `mix app.start` because that requires no additional code and in that case starting the app works fine (there is no database to connect to, or anything like that in the supervision tree). Using `mix run` with a custom function does not start the app, which is probably preferable in the general case.
