### ISSUE TITLE
Multimodal projected embeddings

### ISSUE THREAD

**Issue by lambadalambda** [elixir-nx/bumblebee#274]
I'm trying to use Clip to get embeddings for images and text that I can then compare to one another, but the embeddings generated by Clip with `Bumblebee.Text.text_embedding` and the ones I get from `Bumblebee.Vision.image_embedding` are not compatible. The modal at `Bumblebee.Multimodal.Clip` should be giving out the right kind of embeddings, but I can't use it as a model in either `text_embedding` or `image_embedding`. Is there a way to get those embeddings? If not, can one be added?

**Comment by jonatanklosko** [comment]
@lambadalambda you can do this on Bumblebee main:

```elixir
# Text

{:ok, model_info} =
  Bumblebee.load_model({:hf, "openai/clip-vit-base-patch32"},
    module: Bumblebee.Text.ClipText,
    architecture: :for_embedding
  )

{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, "openai/clip-vit-base-patch32"})

text_serving = Bumblebee.Text.text_embedding(model_info, tokenizer, output_attribute: :embedding)

# Image

{:ok, model_info} =
  Bumblebee.load_model({:hf, "openai/clip-vit-base-patch32"},
    module: Bumblebee.Vision.ClipVision,
    architecture: :for_embedding
  )

{:ok, featurizer} = Bumblebee.load_featurizer({:hf, "openai/clip-vit-base-patch32"})

image_serving = Bumblebee.Vision.image_embedding(model_info, featurizer, output_attribute: :embedding)
```
