### ISSUE TITLE
Support Starcoder Model

### ISSUE THREAD

**Issue by jonastemplestein** [elixir-nx/bumblebee#279]
Related to #278 , it would be amazing if somebody could also look into supporting the [starcoder](https://github.com/bigcode-project/starcoder) model.

The original model is quite big, but there's also a [7B version](https://huggingface.co/TabbyML/StarCoder-7B) and a [1B version](https://huggingface.co/TabbyML/StarCoder-1B)

I've run it through the [repository inspector](https://jonatanklosko-bumblebee-tools.hf.space/apps/repository-inspector) and got the following result:

```
🤷‍♂️ Failed to load, reason: could not match the class name "GPTBigCodeForCausalLM" to any of the supported models, please specify the :module and :architecture options.

Tokenizer
🤷‍♂️ Failed to load, reason: could not match model type "gpt_bigcode" to any of the supported tokenizers, please specify the :module option.

```

Any help is much appreciated <3

**Comment by jonatanklosko** [comment]
This error means that it's not yet implemented in Bumblebee. It looks like `GPTBigCodeForCausalLM` is very similar to GPT2, but with MQA (which we added for Mistral, it's just a question of how to unify the configuration options to accommodate both) and a couple optimisations (some of them may be applicable, but needs a closer look).
