### ISSUE TITLE
Token Classification error in Livebook

### ISSUE THREAD

**Issue by jkwchui** [elixir-nx/bumblebee#343]
Token Classification tasks in Livebook smart cells do not run, and reports 

```
(MatchError) no match of right hand side value: {:error, "no ETag found on the resource"}
```

This is from a fresh notebook, Elixir 1.16.1 / OTP 26, Livebook 0.11.4, Bumblebee 0.4.2.

**Comment by jonatanklosko** [comment]
This is fixed on bumblebee main. As a workaround you can convert the smart cell to code and change unqualified repo names, such as "bert-base-cased" to fully-qualified names as in "google-bert/bert-base-cased". The repo names are also updated on kino_bumblebee main, it's just all waiting for a release.
