### ISSUE TITLE
Support PHI-3

### ISSUE THREAD

**Issue by fire** [elixir-nx/bumblebee#376]
Phi-3-medium-128k-instruct-Q8_0.gguf

Want to test https://huggingface.co/bartowski/Phi-3-medium-128k-instruct-GGUF

> The Phi-3-Medium-128K-Instruct is a 14B parameters, lightweight, state-of-the-art open model trained with the Phi-3 datasets that includes both synthetic data and the filtered publicly available websites data with a focus on high-quality and reasoning dense properties. The model belongs to the Phi-3 family with the Medium version in two variants [4k](https://huggingface.co/microsoft/Phi-3-medium-4k-instruct) and [128K](https://huggingface.co/microsoft/Phi-3-medium-128k-instruct) which is the context length (in tokens) that it can support.

**Comment by jonatanklosko** [comment]
We support Phi-3, but the repo you linked is in GGUF quantized format, which we do not support. You should be able to load from the official checkpoint [microsoft/Phi-3-medium-128k-instruct](https://huggingface.co/microsoft/Phi-3-medium-128k-instruct).

**Comment by jonatanklosko** [comment]
Ah, and you need to be using Bumblebee main branch.
