### ISSUE TITLE
Support for pooling mode CLS token

### ISSUE THREAD

**Issue by nyo16** [elixir-nx/bumblebee#384]
Hello! I am trying to use [BAAI/bge-m3](https://huggingface.co/BAAI/bge-m3) for embeddings. I can load it and get some results but i saw that i need to add a pooling layer for "pooling_mode_cls_token": true.  Can someone point me where I need to add this? I am happy to try to implement it :)

**Comment by jonatanklosko** [comment]
Sounds good, we currently only support `:mean_pooling`:

https://github.com/elixir-nx/bumblebee/blob/78a7dcf79b7859ceeabfc5c1d53d6281bac8215b/lib/bumblebee/text/text_embedding.ex#L64

We can add another strategy `:cls_token_pooling`. A PR is welcome :)

So for bge it would become `output_attribute: :hidden_state, output_pool: :cls_token_pooling`.

**Comment by nyo16** [comment]
Thank you @jonatanklosko I will give a try tonight.

**Comment by jonatanklosko** [comment]
Closed in #385.
