### ISSUE TITLE
How to get bge-m3's sparse embeddings(lexical weights)

### ISSUE THREAD

**Issue by aus70** [elixir-nx/bumblebee#401]
I'm using the following code to compute the dense embeddings using https://huggingface.co/BAAI/bge-m3:

```
{:ok, model_info} = Bumblebee.load_model({:hf, "BAAI/bge-m3"})
{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, "BAAI/bge-m3"})
serving = Bumblebee.Text.text_embedding(model_info, tokenizer, compile: [batch_size: 1, sequence_length: 512])
text = "hello, world"
Nx.Serving.run(serving, text)
```

Is there a way to get the sparse vector (lexical weights) and the multi-vector (ColBERT). Thanks!

**Comment by jonatanklosko** [comment]
The sparse/colbert embeddings are not part of the model itself, they are built on top.

I found an implementation [here](https://github.com/FlagOpen/FlagEmbedding/blob/bd58b6fcedb02fdb7be6927cc55584eb16871e6c/FlagEmbedding/BGE_M3/modeling.py#L357-L363). More specifically, [here](https://github.com/FlagOpen/FlagEmbedding/blob/bd58b6fcedb02fdb7be6927cc55584eb16871e6c/FlagEmbedding/BGE_M3/modeling.py#L76-L86) the model is loaded similarly to `Bumblebee.load_model` and then additional linear layer weights are loaded from separate files in the repo. Finally `sparse_embedding`/`colbert_embedding` methods implement the actual embedding on top of the model output.

It should be possible to implement this by adding layers to the model, loading the linear layer parameters separately and stitching them into the model parameters. Or alternatively on a lower level by converting the model to a function using `Axon.build`, applying the model and then applying the linear layers with its parameters directly.

Given that the weights are stored separately in a non-standard way and I think it should be implemented on top of bumblebee. If it gets integrated into `huggingface/transformers` in a standardized way (which we aim to mirror), then we can add it.
