### ISSUE TITLE
Encapsulate generation config

### ISSUE THREAD

**Issue by jonatanklosko** [elixir-nx/bumblebee#87]
See https://github.com/huggingface/transformers/issues/18655.

Currently the model configuration may include properties that are then used as defaults for generation. This makes it less clear where the defaults come from and unnecessarily makes model configurations larger.

**Comment by jonatanklosko** [comment]
Now that we have more generation strategies, I think ideally we would support something like `strategy: {:contrastive_search, top_k: ..., alpha: ...}`. Having flat options and detecting strategy based on that is rather messy. The thing to figure out is how this ties to loading the config from upstream, but I wouldn't expect anything blocking.

**Comment by josevalim** [comment]
@jonatanklosko that works but we can also do `strategy: :contrastive_search` and then pick the options but that may be hard to validate/document.
