### ISSUE TITLE
Error on linux when attemptting to load models from huggingface

### ISSUE THREAD

**Issue by hansihe** [elixir-nx/bumblebee#98]
When trying out image classification in Livebook, the models seem to fail to load. I am running an up to date install of arch linux with the latest versions of erlang and elixir installed through asdf.

```bash
hansihe:~/ $ asdf current
elixir          1.14.2-otp-25
erlang          25.1.2
```

I'm running the following full code snppet from livebook:

```elixir
Mix.install([
  {:bumblebee, "~> 0.1.0"},
  {:nx, "~> 0.4.1"},
  {:exla, "~> 0.4.1"},
  {:axon, "~> 0.3.1"},
  {:kino, "~> 0.8.0"}
])

Nx.global_default_backend(EXLA.Backend)

{:ok, resnet} = Bumblebee.load_model({:hf, "microsoft/resnet-50"})
{:ok, featurizer} = Bumblebee.load_featurizer({:hf, "microsoft/resnet-50"})

:ok
```

This errors:

```elixir
** (File.RenameError) could not rename from "/tmp/bumblebee_yb7uihnimydvsi55mie2rgydcyih322y" to "/home/hansihe/.cache/bumblebee/huggingface/45jmafnchxcbm43dsoretzry4i.eiztamryhfrtsnzzgjstmnrymq3tgyzzheytqmrzmm4dqnbshe3tozjsmi4tanjthera": cross-domain link
    (elixir 1.14.2) lib/file.ex:766: File.rename!/2
    (bumblebee 0.1.0) lib/bumblebee/huggingface/hub.ex:63: Bumblebee.HuggingFace.Hub.cached_download/2
    (bumblebee 0.1.0) lib/bumblebee.ex:250: Bumblebee.load_spec/2
    (bumblebee 0.1.0) lib/bumblebee.ex:372: Bumblebee.load_model/2
    #cell:a3yfrzehbpz4mpgcbs7lpry7b3sia35g:1: (file)
```

This seems to happen because we are trying to move a file from `/tmp` to `/home`, which are mounted on different filesystems:

```bash
hansihe:~/ $ mount
/dev/nvme0n1p3 on / type ext4 (rw,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
[...]
```

**Comment by josevalim** [comment]
I have pushed a fix.

@jonatanklosko is there a reason why we don't write directly to the final location?

**Comment by hansihe** [comment]
Thanks for the quick fix, seems to have fixed the issue for me! :heart:

**Comment by josevalim** [comment]
Sweet. I will keep it open for now and let @jonatanklosko close it depending if we need the additional op or not.

**Comment by jonatanklosko** [comment]
@josevalim we stream-download the file and if it fails at some point we remove the corrupted file. If we wrote directly to the final location and it fails, we would remove the existing file. But then, if the existing file is outdated it doesn't really matter, so alternatively we could remove the file (and the metadata file) when the download fails, wdyt?

**Comment by josevalim** [comment]
@jonatanklosko i think it makes sense to optimize for the success case rather than the failure one, so copying directly and then removing in case of errors sound good to me!

**Comment by jonatanklosko** [comment]
Done in 8331b0f48766538be865e72384126e1aeb1c663b.

**Comment by fire** [comment]
This happens for me too. How I install this update?

**Comment by fire** [comment]
```elixir
Mix.install([
  {:bumblebee, git: "https://github.com/elixir-nx/bumblebee.git", tag: "8331b0f48766538be865e72384126e1aeb1c663b"},
  {:nx, "~> 0.4.1"},
  {:exla, "~> 0.4.1"},
  {:kino, "~> 0.8.0"}
])
```
