### ISSUE TITLE
Unable to configure XLA_TARGET=cuda118 to use GPU

### ISSUE THREAD

**Issue by xrd** [elixir-nx/bumblebee#99]
I've been trying to use XLA_TARGET=cuda118 within a livebook app.

I'm running using the livebook github repository (https://github.com/livebook-dev/livebook.git, my HEAD is 361455cd4eb1b527e6fd04d5c51f2901cbb4ed90). 

I am running using `XLA_TARGET=cuda118 MIX_ENV=prod mix phx.server`.

I also tried setting `XLA_TARGET=cuda118` inside the environment variables of the livebook settings.

No matter what I do, when I run an example Neural Network, it always prints out:

```
14:30:19.336 [info] TfrtCpuClient created.
```

If I'm targeting the GPU, I assume it would print out a different client, right?

Notebook dependencies and setup are:

```
Mix.install(
  [
    {:kino_bumblebee, "~> 0.1.0"},
    {:exla, "~> 0.4.1"}
  ],
  config: [nx: [default_backend: EXLA.Backend]]
)
```

Bumblee seems to be the correct version:

```
Application.spec(:kino_bumblebee, :vsn)
'0.1.0'
```

Also:

```
Livebook v0.8.0
Elixir v1.14.2
```

I believe I have a supported version of nvidia on the host:

```
$ nvidia-smi 
Fri Dec  9 14:37:59 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   37C    P8     6W / 120W |     15MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     14189      G   ...xorg-server-1.20.14/bin/X        9MiB |
|    0   N/A  N/A     14217      G   ...hell-43.1/bin/gnome-shell        2MiB |
+-----------------------------------------------------------------------------+
```

**Comment by seanmor5** [comment]
What if you set cuda explicitly in your config?

```
  config: [
    nx: [
      default_backend: EXLA.Backend,
      default_defn_options: [compiler: EXLA, client: :cuda]
    ]
  ],
  system_env: [
    XLA_TARGET: "cuda"
  ]
```

**Comment by josevalim** [comment]
You can also run: `EXLA.Client.get_supported_platforms()` and see if CUDA is listed. If it isn't, for some reason XLA is not identifying your GPU device.

**Comment by josevalim** [comment]
And additionally `EXLA.Client.default_name()` to get the name of the default one.

**Comment by zolrath** [comment]
When I encountered this I had run the Livebook before I had set the `XLA_TARGET`, so XLA was already compiled with only CPU support. Even after adding the `XLA_TARGET` and ensuring I had CUDA and cuDNN installed properly I would get `14:30:19.336 [info] TfrtCpuClient created.`.

I solved this by deleting the `xla` and `mix` folders in `~/.cache`, as I couldn't see a clean way to run `mix deps.clean xla --build` in Livebook.

**Comment by josevalim** [comment]
@jonatanklosko we should consider the `XLA_TARGET` in the cache key, right?

**Comment by xrd** [comment]
@zolrath Yes, that is what must have happened to me as well. I did get CUDA at first, and then could not switch back to it no matter what I tried. Thanks everyone for your help, and thanks @seanmor5 and @josevalim for an amazing project!

**Comment by jonatanklosko** [comment]
@josevalim ohh I've just realised that setting the env var and restarting runtime is not enough (unless the env var is set in Mix.install options). That's because we changed XLA to look at the initial `XLA_TARGET`, rather than every time it compiles. So in a mix project that would require `mix deps.clean xla --build` and for mix install `force: true`.

**Comment by josevalim** [comment]
Do you remember why we did such change?

**Comment by jonatanklosko** [comment]
Actually what I was remembering is `XLA_BUILD` (https://github.com/elixir-nx/nx/issues/845#issuecomment-1193780545). The issue with `XLA_TARGET` is that we compile dependencies only once, specifically `exla`.

Inside the `exla` project if you call `mix compile` with a different `XLA_BUILD` it will pick up the new version, but if you call `mix compile` in a project that depends on `exla`, it wouldn't pick up the change, since `exla` doesn't recompile.

**Comment by josevalim** [comment]
But it works if we pass it to Mix.install/2 or force build, right?

maybe we should have an option to “force build” from Livebook UI? Maybe a drop down on the “Reconnect and setup”?

**Comment by xrd** [comment]
I'm able to use cuda now, shall I close it?

**Comment by josevalim** [comment]
We will close it @xrd as soon as we figure out how to improve the user experience :)

**Comment by josevalim** [comment]
Actually, one way to improve this would be to add:

```
system_env: %{"XLA_TARGET" => System.get_env("XLA_TARGET")}
```

this will enforce system differences to be picked up.

**Comment by josevalim** [comment]
So I guess the best option is some UI to force installation the next install?

**Comment by jonatanklosko** [comment]
That could be useful in other cases too. Would we modify the code on the fly to include `force: true`?

**Comment by josevalim** [comment]
@jonatanklosko there is an env var called MIX_INSTALL_FORCE, we can set it to "true" before we evaluate.

**Comment by josevalim** [comment]
Moved to Livebook backlog: https://github.com/livebook-dev/livebook/issues/1579
